### PR TITLE
added method 'transformPoint' to UMAP.yaml

### PR DESCRIPTION
**Pull request by tedmoore**
This was prompted to me by the SCDoc render, and there's more where that came from, so before I dig in, just want to make sure I'm not missing anything. 

Is this the right idea for fixing missing stuff in the yaml?

### CODE REVIEW

**Comment by tedmoore** [comment]
@ weefuzzy got it. i've seen the `#<method>` in some other YAMLs. would it be good for me to do a find all and remove them?

**Comment by weefuzzy** [comment]
Maybe do a quick regex  search in folder and report back how many there are. That might have some bearing on how urgent making this work is!

**Comment by tedmoore** [comment]
i spy just 4 docs
Screenshot 2022-02-01 at 14 14 27

**Comment by weefuzzy** [comment]
Ok, not a 🔥 🔥 🚒 🚨 🚨 🚨 🚨  by any means.

**Pull request merged**
