### PR TITLE
RobustScale

### PR DESCRIPTION
**Pull request by tedmoore**

### CODE REVIEW

**Review by jamesb93 — CHANGES_REQUESTED** [review]
It seems the description has content which is more suited to the discussion. It is quite long and will not render well in Max but probably fine in SC. Can't speak for PD yet.

I think that much of this kind of text should be moved to a discussion section with a terser description similar to Standardise being the description.

**Comment by jamesb93** [comment]
> I see. Since I'm doing the SC help right now I'm not looking at what these look like in Max. I was thinking that when the Max translations happen that's when any Max-related issues will be discovered. In SC there is no distinction between discussion and description.

I see that now. In Max the name, digest, description get made into the header for the first page of each help file:

image


> Is the idea that the description is one sentence and the discussion is the rest?

Exactly, because the discussion then formulates the longer meat of the reference.

image

**Comment by tedmoore** [comment]
cool cool.

**Comment by tremblap** [comment]
cool. 
Typo: qartile
typo: no space after fullstop in last stencence.
the sentence "will scale the data to +/- the provided centiles" is cryptic as in the note I gave on the PR of the learn platform. we can tweak it accordingly.

I see the bidirect graphs are back, love them.

**Pull request merged**
