### PR TITLE
PCA inverseTransformPoint

### PR DESCRIPTION
**Pull request by tedmoore**

### CODE REVIEW

**Comment by jamesb93** [comment]
Don't think this is in Max AFAIK, so will need to await that.

**Comment by tremblap** [comment]
I don't understand the comment about it not being in Max. as it stands it automagically appears in max and pd - are you talking about their help file?

**Comment by tedmoore** [comment]
> as it stands it automagically appears in max and pd

This is what I understood to be the case as well. It is true that it won't be in the help files. This PR is just for it to appear in the various references (which is the help file in SC). 

Putting examples in the various CCEs is still yet to be done.

**Comment by jamesb93** [comment]
> > as it stands it automagically appears in max and pd
> 
> This is what I understood to be the case as well. It is true that it won't be in the help files. This PR is just for it to appear in the various references (which is the help file in SC). 
> 
> Putting examples in the various CCEs is still yet to be done. And I'm thinking that it will happen when we come around to the PCA helpfile revamps (it's on the list still!)

Ah okay this my misunderstanding about which work needed to be done for that message to "go live" and didn't realise it was active. IIRC transformpoint was going to receive the possibility of adding optional arguments to do inversion so I'm not sure how this plays with that, or if it's just an alias.

**Comment by tremblap** [comment]
definitely a new message for inverse, and the same for all transformers (I added the ticket)

because this breaks nothing, and it is merged already, I'll comment on this doc issue, then we can merge and make issues for all PCA helpfiles to be updated.

savvy?

**Review by jamesb93 — APPROVED** [review]

**Review by tremblap — CHANGES_REQUESTED** [review]
ok this is good, but raises a question for @weefuzzy : I think we should have an inverseTransform method too, to be consistent. we could document it here at the same time.

**Review by weefuzzy — CHANGES_REQUESTED** [review]
We'll need the dataset version as well

**Pull request merged**
