### PR TITLE
[Docs] Move Description to Discussion for BufFlatten

### PR DESCRIPTION
**Pull request by jamesb93**
Much of the long textin the description (which should be terse) is moved to the discussion. This will help the rendering of text in Max help files where it is currently quite long.﻿

### CODE REVIEW

**Review by tedmoore — APPROVED** [review]
Ah yes. This will render the same in SC docs so no need to PR this (as far as I'm concerned). If you need to do things  for the translation that won't affect how it renders in SC you can just go for it!

**Comment by jamesb93** [comment]
I think this is actually superfluous and Owen changed it in another PR.

**Comment by tedmoore** [comment]
i don't understand

**Comment by jamesb93** [comment]
https://github.com/flucoma/flucoma-docs/pull/107/files

Check the first set of diffs here

**Pull request closed without merging**
