### PR TITLE
Json driver

### PR DESCRIPTION
**Pull request by weefuzzy**
@jamesb93 @tedmoore here's some untested code for doing the raw JSON output. I think the CMake target to try would be `MAKE_RAW_REF`. Give it a shot, see what breaks. I've put the branch for this on the shared repo, so we can all hack on it to our hearts' content.

### CODE REVIEW

**Comment by jamesb93** [comment]
Will check out this soon.

**Comment by jamesb93** [comment]
I got this error:

```sh
FAILED: CMakeFiles/MAKE_RAW_REF /Users/james/dev/flucoma/docs/build/CMakeFiles/MAKE_RAW_REF 
cd /Users/james/dev/flucoma/docs && /opt/homebrew/Cellar/cmake/3.22.1/bin/cmake -E make_directory "" && /Users/james/.virtualenvs/flucoma/bin/python3.9 -mflucoma.MakeRef raw /Users/james/dev/flucoma/docs/build/json /Users/james/dev/flucoma/docs/doc "" /Users/james/dev/flucoma/docs/flucoma/doc/templates
Error creating directory "".
ninja: build stopped: subcommand failed.
```

**Comment by weefuzzy** [comment]
The problem is here:

https://github.com/flucoma/flucoma-docs/blob/0e970cb811e59e541ec41348e69c9302af254a45/flucoma/doc/raw/driver.py#L15-L18

maybe try resolving the path or somethng?

**Comment by jamesb93** [comment]
No lock resolving that path object with either:

`.resolve()` or a chain of `.expanduser().resolve()`

**Comment by weefuzzy** [comment]
Are we actually passing a blank string in as the output path? Seems like we should catch such an eventuality and convert to `'.'` if so.

**Comment by jamesb93** [comment]
I think we are just putting an empty string. I'll try catching the case

**Comment by jamesb93** [comment]
Even with:

```py
    if path == '' or path == None:
        path = '.'
```

I get the same error

**Comment by weefuzzy** [comment]
Ok, sorry. That wasn't the problem. I'd forgotten that we need a CMake variable to set the output path. Which is terrible, but hey. 

This gives me output now. Whether it's ideal is another issue, given that it contains all the SC example code at the moment, making it bigger than we probably want. Suggest we do some pruning before writing out.

**Review by jamesb93 — APPROVED** [review]

**Pull request merged**
