### PR TITLE
improve build time

### PR DESCRIPTION
**Pull request by weefuzzy**
Uses a couple of tactical forward declarations to improve on the awful build time a bit . Lots of diff due to tidying up and formatting the file, but this is the bit that matters: 

https://github.com/weefuzzy/flucoma-docs/blob/d10776e19e429036e659073567a558e13f043a06/include/FluidParameterDump.hpp#L38-L44

@ reviewers, not much needed except to confirm that this still builds for you (and, preferably, more quickly than it did)

### CODE REVIEW

**Comment by tremblap** [comment]
Tip of dev in core, plus this, it does feel faster but it hangs at the end: 

```
FAILED: _deps/flucoma-docs-build/CMakeFiles/MAKE_MAX_REF
cd "/Users/pa/Documents/documents@hudd/research/projects/fluid corpus navigation/research/fluid_paramdump" && /usr/local/Cellar/cmake/3.19.0_1/bin/cmake -E make_directory "/Users/pa/Documents/documents@hudd/research/projects/fluid corpus navigation/research/flucoma-max/build/max_ref" && /Users/pa/anaconda3/bin/python -mflucoma.MakeRef max "/Users/pa/Documents/documents@hudd/research/projects/fluid corpus navigation/research/flucoma-max/build/json" "/Users/pa/Documents/documents@hudd/research/projects/fluid corpus navigation/research/fluid_paramdump/doc" "/Users/pa/Documents/documents@hudd/research/projects/fluid corpus navigation/research/flucoma-max/build/max_ref" "/Users/pa/Documents/documents@hudd/research/projects/fluid corpus navigation/research/fluid_paramdump/flucoma/doc/templates"
Traceback (most recent call last):
  File "/Users/pa/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/pa/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/pa/Documents/documents@hudd/research/projects/fluid corpus navigation/research/fluid_paramdump/flucoma/MakeRef.py", line 18, in <module>
    from flucoma.doc.validate.object import validate_object
  File "/Users/pa/Documents/documents@hudd/research/projects/fluid corpus navigation/research/fluid_paramdump/flucoma/doc/validate/object.py", line 12, in <module>
    from schema import Schema, Optional, Use
ModuleNotFoundError: No module named 'schema'
```

**Comment by weefuzzy** [comment]
It is absolutely something python related. You don't have all the (updated) required dependencies installed, so `dev` won't be working for you either. Specifically you're missing the `schema` package, but that might not be all: there's now a `requirements.txt` that can be used to install everything in one go with `pip`:

```
pip install -r requirements.txt 
```
 If you're using `conda` to manage your environments, you can use the `requirements.txt` with conda when making a new environment but not for ad hoc package installation. 

---

```
/flucoma/doc/validate/object.py", line 12, in <module>
    from schema import Schema, Optional, Use
ModuleNotFoundError: No module named 'schema'
```

**Comment by tremblap** [comment]
So. I updated my conda, and I have everything except that Jinja2 is stalled at 3.0.2 (even via update which actually downgrades docutils)

the largest problem is schema, which doesn't have a conda repo - I google and there is no conda install instruction here (https://pypi.org/project/schema/) so is it safe to pip it?

**Comment by tremblap** [comment]
so. I've pip'd schema after updating conda and I still get an error this time probably to do with versions that do not update for the platform

```
FAILED: _deps/flucoma-docs-build/CMakeFiles/MAKE_MAX_REF
cd "/Users/pa/Documents/documents@hudd/research/projects/fluid corpus navigation/research/fluid_paramdump" && /usr/local/Cellar/cmake/3.19.0_1/bin/cmake -E make_directory "/Users/pa/Documents/documents@hudd/research/projects/fluid corpus navigation/research/flucoma-max/build/max_ref" && /Users/pa/anaconda3/bin/python -mflucoma.MakeRef max "/Users/pa/Documents/documents@hudd/research/projects/fluid corpus navigation/research/flucoma-max/build/json" "/Users/pa/Documents/documents@hudd/research/projects/fluid corpus navigation/research/fluid_paramdump/doc" "/Users/pa/Documents/documents@hudd/research/projects/fluid corpus navigation/research/flucoma-max/build/max_ref" "/Users/pa/Documents/documents@hudd/research/projects/fluid corpus navigation/research/fluid_paramdump/flucoma/doc/templates"
Traceback (most recent call last):
  File "/Users/pa/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/pa/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/pa/Documents/documents@hudd/research/projects/fluid corpus navigation/research/fluid_paramdump/flucoma/MakeRef.py", line 99, in <module>
    main(sys.argv[1:])
  File "/Users/pa/Documents/documents@hudd/research/projects/fluid corpus navigation/research/fluid_paramdump/flucoma/MakeRef.py", line 66, in main
    driver = importlib.import_module('.driver', f'flucoma.doc.{args.host}')
  File "/Users/pa/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/pa/Documents/documents@hudd/research/projects/fluid corpus navigation/research/fluid_paramdump/flucoma/doc/max/driver.py", line 13, in <module>
    from flucoma.doc.rst.html import FluidHTMLWriter, rst_filter
  File "/Users/pa/Documents/documents@hudd/research/projects/fluid corpus navigation/research/fluid_paramdump/flucoma/doc/rst/html.py", line 17, in <module>
    from jinja2 import pass_context
ImportError: cannot import name 'pass_context' from 'jinja2' (/Users/pa/anaconda3/lib/python3.8/site-packages/jinja2/__init__.py)
```

**Comment by weefuzzy** [comment]
I'm moving this to a new issue as it relates to the `dev` branch, not this PR.

**Comment by tremblap** [comment]
this PR seems to add a file entitled flucoma-makeref.log
should it be added to the .gitignore list of this PR?

**Comment by weefuzzy** [comment]
That's a mistake inherited from `dev`. It's in the `.gitignore` but seemed to have got added anyway. I'll deal with it at source.

**Comment by jamesb93** [comment]
Let me know if / when you want to test this on my machine or with CI @weefuzzy . Should be as easy as making a dummy action and letting rip.

**Comment by weefuzzy** [comment]
Have at it!

**Comment by jamesb93** [comment]
Wow, much much faster! Nice one. I use `virtualfish` and it soaked up my environment au naturel 🥳 

Is there more work to be done on this front or is this mergable in its current state (assuming working).

**Comment by tedmoore** [comment]
👍

**Comment by weefuzzy** [comment]
> Is there more work to be done on this front or is this mergeable in its current state (assuming working).

Should be mergeable, if everyone's happy enough

**Comment by tedmoore** [comment]
go for it

**Pull request merged**
