### PR TITLE
YAML 2 reStructuredText

### PR DESCRIPTION
**Pull request by weefuzzy**
A first (still messy) push of the conversion and parsing machinery, so folk can have a look at what it produces and have a chance to opine. 

There's two python files here: 
* `flucoma/doc/rst/parse_object.py` uses docutils to parse an rst file as generated (which we'll obviously need to do) 
* `flucoma/yaml2rst.py` converts the contents of the `doc` folder to rst (examples below), then makes sure it can parse the result back in, and prints out a bit-by-bit diff with the original object so we can verify that there are only trivial differences of white space between the source and translated version 

One would invoke it like `python -m  flucoma.yaml2rst > conversion.log` (or print to stdout, whatever). 

There's a slight difference in the output compared to what I originally suggested. Instead of controls and messages being represented by `directive`s like this 
```reStructuredText
.. control blah 
   blah blah 

.. message blah 
   blah blah 
```

I decided to treat them as `field`s like 
```reStructuredText
:control blah:
   blah blah 

:message blah:
   blah blah 
```

Which IMO gives more consistency with the rest of the syntax, and is easier to code. And it get picked up by syntax highlighters 😉 

Output examples: 

<details>
<summary>Gain:</summary>

```reStructuredText
:digest: Real-Time Buffered Gain Changer
:species: transformer
:sc-categories: UGens>Algebraic, Libraries>FluidDecomposition, UGens>Buffer
:sc-related: Guides/FluidCorpusManipulationToolkit,Classes/UnaryOpFunction
:description: This class implements a sanity test for the FluCoMa Real-Time Client Wrapper.
:see-also: 
:discussion: 
:process: The audio rate version of the object.
:output: Same as input, multiplied by the gain factor.


:control in:

   The input to be processed

:control gain:

   Audio or control rate change of the gain.
```

</details>

<details>
<summary>MDS: </summary>

```reStructuredText
:digest: Dimensionality Reduction with Multidimensional Scaling
:species: data
:sc-categories: Dimensionality Reduction, Data Processing
:sc-related: Classes/FluidMDS, Classes/FluidDataSet
:see-also: 
:description: 
   Multidimensional scaling of a :fluid-obj:`DataSet`

   https://scikit-learn.org/stable/modules/manifold.html#multi-dimensional-scaling-mds



:control numDimensions:

   The number of dimensions to reduce to

:control distanceMetric:

   The distance metric to use (integer, 0-6, see flags above)


:message fitTransform:

   :arg sourceDataSet: Source data, or the DataSet name

   :arg destDataSet: Destination data, or the DataSet name

   :arg action: Run when done

   Fit the model to a :fluid-obj:`DataSet` and write the new projected data to a destination FluidDataSet.
```

</details>

<details>
<summary>BufNMF: </summary>

```reStructuredText
:digest: Buffer-Based Non-Negative Matrix Factorisation on Spectral Frames
:species: buffer-proc
:sc-categories: Libraries>FluidDecomposition, UGens>Buffer
:sc-related: Guides/FluidCorpusManipulationToolkit, Classes/FluidNMFMatch, Classes/FluidNMFFilter
:see-also: NMFMatch, NMFFilter
:description: Decomposes the spectrum of a sound into a number of components using Non-Negative Matrix Factorisation (NMF)
:discussion: 
   NMF has been a popular technique in signal processing research for things like source separation and transcription (see Smaragdis and Brown, Non-Negative Matrix Factorization for Polyphonic Music Transcription.), although its creative potential is so far relatively  unexplored.

   The algorithm takes a buffer in and divides it into a number of components, determined by the components argument. It works iteratively, by trying to find a combination of spectral templates ('bases') and envelopes ('activations') that yield the original magnitude spectrogram when added together. By and large, there is no unique answer to this question (i.e. there are different ways of accounting for an evolving spectrum in terms of some set of templates and envelopes). In its basic form, NMF is a form of unsupervised learning: it starts with some random data and then converges towards something that minimizes the distance between its generated data and the original:it tends to converge very quickly at first and then level out. Fewer iterations mean less processing, but also less predictable results.

   The object can return either or all of the following:
   	* a spectral contour of each component in the form of a magnitude spectrogram (called a basis in NMF lingo);
   	* an amplitude envelope of each component in the form of gains for each consecutive frame of the underlying spectrogram (called an activation in NMF lingo);
   	* an audio reconstruction of each components in the time domain.

   The bases and activations can be used to make a kind of vocoder based on what NMF has 'learned' from the original data. Alternatively, taking the matrix product of a basis and an activation will yield a synthetic magnitude spectrogram of a component (which could be reconsructed, given some phase informaiton from somewhere).

   Some additional options and flexibility can be found through combinations of the basesMode and actMode arguments. If these flags are set to 1, the object expects to be supplied with pre-formed spectra (or envelopes) that will be used as seeds for the decomposition, providing more guided results. When set to 2, the supplied buffers won't be updated, so become templates to match against instead. Note that having both bases and activations set to 2 doesn't make sense, so the object will complain.

   If supplying pre-formed data, it's up to the user to make sure that the supplied buffers are the right size:
     * bases must be `(fft size / 2) + 1` frames and `(components * input channels)` channels
     * activations  must be `(input frames / hopSize) + 1` frames and `(components * input channels)` channels

   In this implementation, the components are reconstructed by masking the original spectrum, such that they will sum to yield the original sound.

   The whole process can be related to a channel vocoder where, instead of fixed bandpass filters, we get more complex filter shapes that are learned from the data, and the activations correspond to channel envelopes.

:process: This is the method that calls for the factorisation to be calculated on a given source buffer.
:output: Nothing, as the various destination buffers are declared in the function call.


:control source:

   The index of the buffer to use as the source material to be decomposed through the NMF process. The different channels of multichannel buffers will be processing sequentially.

:control startFrame:

   Where in the srcBuf should the NMF process start, in sample.

:control numFrames:

   How many frames should be processed.

:control startChan:

   For multichannel srcBuf, which channel should be processed first.

:control numChans:

   For multichannel srcBuf, how many channel should be processed.

:control resynth:

   The index of the buffer where the different reconstructed components will be reconstructed. The buffer will be resized to `components * numChannelsProcessed` channels and `sourceDuration` lenght. If `nil` is provided, the reconstruction will not happen.

:control bases:

   The index of the buffer where the different bases will be written to and/or read from: the behaviour is set in the following argument. If `nil` is provided, no bases will be returned.

:control basesMode:

   This flag decides of how the basis buffer passed as the previous argument is treated.

   :enum:

      :0:
         The bases are seeded randomly, and the resulting ones will be written after the process in the passed buffer. The buffer is resized to `components * numChannelsProcessed` channels and `(fftSize / 2 + 1)` lenght.

      :1:
         The passed buffer is considered as seed for the bases. Its dimensions should match the values above. The resulting bases will replace the seed ones.

      :2:
         The passed buffer is considered as a template for the bases, and will therefore not change. Its bases should match the values above.

:control activations:

   The index of the buffer where the different activations will be written to and/or read from: the behaviour is set in the following argument. If `nil` is provided, no activation will be returned.

:control actMode:

   This flag decides of how the activation buffer passed as the previous argument is treated.

   :enum:

      :0:
         The activations are seeded randomly, and the resulting ones will be written after the process in the passed buffer. The buffer is resized to `components * numChannelsProcessed` channels and `(sourceDuration / hopsize + 1)` lenght.

      :1:
         The passed buffer is considered as seed for the activations. Its dimensions should match the values above. The resulting activations will replace the seed ones.

      :2:
         The passed buffer is considered as a template for the activations, and will therefore not change. Its dimensions should match the values above.

:control components:

   The number of elements the NMF algorithm will try to divide the spectrogram of the source in.

:control iterations:

   The NMF process is iterative, trying to converge to the smallest error in its factorisation. The number of iterations will decide how many times it tries to adjust its estimates. Higher numbers here will be more CPU expensive, lower numbers will be more unpredictable in quality.

:control windowSize:

   The window size. As NMF relies on spectral frames, we need to decide what precision we give it spectrally and temporally, in line with Gabor Uncertainty principles. http://www.subsurfwiki.org/wiki/Gabor_uncertainty

:control hopSize:

   The window hop size. As NMF relies on spectral frames, we need to move the window forward. It can be any size but low overlap will create audible artefacts.

:control fftSize:

   The inner FFT/IFFT size. It should be at least 4 samples long, at least the size of the window, and a power of 2. Making it larger allows an oversampling of the spectral precision.

:control winType:

   The inner FFT/IFFT windowing type (not implemented yet)

:control randSeed:

   The NMF process needs to seed its starting point. If specified, the same values will be used. The default of -1 will randomly assign them. (not implemented yet)

:control action:

   A Function to be evaluated once the offline process has finished and all Buffer's instance variables have been updated on the client side. The function will be passed [resynth, bases, activations] as an argument.
```

</details>

### CODE REVIEW

**Comment by weefuzzy** [comment]
slow down, I'm still working on it

**Comment by tedmoore** [comment]
The rst looks great. You're very right is it is preferable to the yaml.

**Comment by tremblap** [comment]
the example code, with the colour syntax, is a great readability improvement. All my usual worries about tables and other things, cross-reference will look... am I right to think that this would work (the keyword buffer being Array in pd doc)

:digest: :Buffer:-Based Non-Negative Matrix Factorisation on Spectral Frames

**Comment by jamesb93** [comment]
I haven't tested this in practice but I really like the syntax and the fact we don't have to transform the amalgam of YAML + RST but just one consistent format.

**Comment by jamesb93** [comment]
> MDS

You would do:

```rst
:digest: 
    :Buffer:-Based Non-Negative Matrix Factorisation on Spectral Frames
```

and I think the whitespace would delineate for you

**Comment by weefuzzy** [comment]
Tables and  cross references don't change – they were already in rst. 

The replacement for `buffer` is currently spelled `|buffer|` rather than `:buffer:` because it's a different kind of thing. We could achieve `:buffer:` instead, but it would take some pythoning

**Comment by jamesb93** [comment]
> Tables and cross references don't change – they were already in rst.
> 
> The replacement for `buffer` is currently spelled `|buffer|` rather than `:buffer:` because it's a different kind of thing. We could achieve `:buffer:` instead, but it would take some pythoning

I was misled :P `|buffer|` is way clearer than `:buffer:`

**Review by tremblap — APPROVED** [review]

**Review by tedmoore — APPROVED** [review]

**Comment by weefuzzy** [comment]
Ok 😅 I think I'm happy now. There was a fun discovery that, besides all the normal transient breakages, a whole bunch of stuff just hasn't been appearing in the SC docs on `dev`. 

Running diffs against the generated docs on `dev` I'm now only seeing differences in whitespace or human stuff I've fixed in the docs whilst looking at XML trees. 


If everyone beleives me, I'll merge. If someone with scary good concentration like @tremblap wants to make sure beforehand, then have at it 

-----

A widespread thing that **I haven't fixed** is that there's quite a lot stuff marked up with single backticks (like a inline code thing in markdown) where we probably mean double backticks, i.e. 

```reStructuredText
``this`` not `this`
```

The double backticks are what rst calls [inline literals](https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#inline-literals), i.e. what we normally use for inline code stuff. [Single backticks are a different beast](https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#interpreted-text) – tl;dr is that their meaning is flexible: one can denote an explicit way to interpret them with a 'role' (like `:fluid-obj:`), otherwise docutils will use the default role.  When we parse *could* set this default role to emit literals, but this would make our files less portable.

**Comment by tedmoore** [comment]
I believe you

**Comment by weefuzzy** [comment]
you're very trusting

**Comment by jamesb93** [comment]
I believe _in_ you.

**Comment by weefuzzy** [comment]
I shall interpret PA's silence as approval and merge then...

**Comment by tremblap** [comment]
what's the plan for the single tick to double tick conversion? isn't is something we could regex? I can imagine there must be very little single ticks that are valid in our current code

**Comment by weefuzzy** [comment]
Haha, so it was, sorry. Had gone a bit glass eyed by then. It was just to take advantage of your observational keenness before pressing the button

**Comment by weefuzzy** [comment]
> what's the plan for the single tick to double tick conversion? isn't is something we could regex? I can imagine there must be very little single ticks that are valid in our current code

Yeah, it can totally be regexed by whomever's working on docs.

**Comment by jamesb93** [comment]
To save yourself the pain you could just `Cmd+F` for ` with a strict match which is the same result.

**Comment by tremblap** [comment]
the beaut of consecutive rejection is that the tick can be the neigbourg of anything else :)

**Comment by jamesb93** [comment]
That's what a strict match is

**Comment by tremblap** [comment]
`(?!`)\w*`(?!`) finds the single quoted words. it is fun. now I don't know on what to search it :)

**Comment by jamesb93** [comment]
nice or you could do:

^`$

**Comment by jamesb93** [comment]
Not sure if Atom has it but in VSCode you can regex search files either globally or per-file for doing the replacements :)

image

**Comment by tremblap** [comment]
I'm surprised that your strict match doesn't find the 2nd line. Anyway. in Atom I can search in the whole folder and then see the result in a separate clickable window. I'll check in docs if I can find my string :)

**Comment by tremblap** [comment]
so in the flucoma-doc/doc/ I have 120 single-tick words which i can replace automagically
`(?!`)(\w*)`(?!`)
with
``$1``
and it shows me a great preview like so:
Screenshot 2022-02-09 at 22 02 13

if I read right, these are all valid and should all be doubleticks, right @weefuzzy ?

**Comment by jamesb93** [comment]
I'm not clear on what @weefuzzy said and I tried re-reading his larger comment above but I'm not sure if :fluid-obj:`Thing` needs to be double backticked?

**Comment by tremblap** [comment]
I'll check with him tomorrow. I can remove that from the search easily if that is not the case but there are still all the other cases. Now is bedtime for me.

**Comment by tremblap** [comment]
so I will run this, test and push, right?

**Comment by weefuzzy** [comment]
be my guest – but not to this branch, it's just a side issue. I don't think it actually breaks anything horribly

**Comment by tremblap** [comment]
done and will do a PR as a good citizen. I'll ask @jamesb93 to read

**Pull request merged**
