### PR TITLE
Standardize RST & SC examples

### PR DESCRIPTION
**Pull request by tedmoore**

### CODE REVIEW

**Review by jamesb93 — CHANGES_REQUESTED** [review]
The text looks much clearer to me. There is however no discussion zone and only the description. Is there more information we could put into the discussion?

**Comment by jamesb93** [comment]
> What would you like for it to say?

I'm not sure, and looking at many of the data orientated help files lots are missing a discussion.

In the future I anticipate that these will at least be filled with a link to the learn platform reference (either manually or programatically)

**Comment by tremblap** [comment]
deffo a link to the learn platfom is needed.

a sentence saying how the std and std of the data is used, like in the learn. mean = 0 and stddev = 1

otherwise it is terse. and good. the graphs are back (or were never gone) and I love tem

**Comment by jamesb93** [comment]
> deffo a link to the learn platfom is needed.

https://github.com/flucoma/flucoma-docs/pull/120

**Pull request merged**
