### PR TITLE
Add enum rendering to SC control jinja template

### PR DESCRIPTION
**Pull request by weefuzzy**
@tedmoore fix for #84

### CODE REVIEW

**Comment by tedmoore** [comment]
@weefuzzy This looks great, but it needs to have numbers!

Screenshot 2022-02-21 at 10 07 05

**Comment by weefuzzy** [comment]
if there's a way of starting an scdoc `numberedlist::` from 0, then by all means change the tag in the jinja template. Otherwise, I'd defer until we can do more complicated rendering

**Comment by tedmoore** [comment]
i'll investigate

**Comment by tedmoore** [comment]
`table::` is looking very nice.
Screenshot 2022-02-21 at 10 18 53

**Pull request merged**
