### PR TITLE
HPSS Help file (RST) and SC examples

### PR DESCRIPTION
**Pull request by tedmoore**
If anyone has a really keen `maskingMode` = 2 example that'd be useful!

### CODE REVIEW

**Comment by tremblap** [comment]
I thought the drums example was sounding fun, no? it was kind of splitting the reverb from the pitch. I can try to make it again with better coefficients

**Review by tremblap — CHANGES_REQUESTED** [review]
'set to 2 (inter-dependant thresholds). See below.' this is clumsy english. maybe just 'see below in the example section' ? but that creates a problem for the pd and max document using the same text so maybe we need an explanation in the text part too.

otherwise it is good, if a little verbose - there will be a clash of culture between the Max style of @jamesb93 when it comes to translating I think.

finally, there is an error: maskmode 2 is binary of sort, definitely not a soft mask for real with continuous values. We can look at the code together but I think we should find a way to explain it clearer how the 2 binary masks fight each other and generate a residual in the conflicting zones.

**Comment by tedmoore** [comment]
> finally, there is an error: maskmode 2 is binary of sort, definitely not a soft mask for real with continuous values.

This is what the RST said before I arrived to it: 

`Inter-dependent mode - Thresholds can be varied independently, but are coupled in effect. Binary masks are made for each of the harmonic and percussive components, and the masks are converted to soft at the end so that everything null sums even if the params are independent, that is what makes it harder to control. These aren't guranteed to cover the whole sound; in this case the 'leftovers' will placed into a third buffer.`

It looks to me like they are turned into soft masks at the end:

https://github.com/flucoma/flucoma-core/blob/cdbe03c292dbf220dbc46c3c41aedc60451fe9cb/include/algorithms/public/HPSS.hpp#L127

**Comment by tremblap** [comment]
this is interesting because for me it is binary. let me explain:
- in the classic, a bin in time can be any ratio of P/H (line 103)
- in the couped, a bin can either be P or H (line 109-113) with a threshold of truth
- in the final mode, which was an odd addition after my many hours of playing with the python prototype, we make binary thresholds and inclusion, then we normalise their sum. so it has a binary mask sound, just scaled - a bin can be assigned binarily to P (vs res) and H (vs res) and then will removed from res (line 125-126 cannot go back to true as it is multiplying 0) so the truth table at that state is that there are 4 values possible
- P1 H0 R0
- P0 H1 R0
- P1 H1 R0
- P0 H0 R1

and the normalisation (line 127-128) scales the 3rd case to match - so that is why it sounds binary as there are only 3 values for each bin's magnitude (0 0.5 1)

calling that a softmask is pushing it a little especially as it doesn't match the phenomenology of what we actually hear...

**Comment by tremblap** [comment]
it is a ternary mask, but that is ugly :)

**Comment by tedmoore** [comment]
How about:

`Alongside the harmonic and percussive components, a third component containing "residual" is returned. First, binary masks are made separately for the harmonic and percussive components using different thresholds (set with the respective ``harmThresh-`` and ``percThresh-`` parameters below). Because these masks aren't guaranteed to represent the entire spectrogram, any residual energy is considered as a third output.  The independently created binary masks are converted to soft masks at the end of the process so that everything null sums.`

I still think soft mask is the right description. Isn't a binary mask binary because it only has two states? It's not a binary mask be cause we have two of them. The masks in this output could be values between 0.0-1.0. So they're soft, even if just not as smoothly continuous as in mode 0?

**Comment by tremblap** [comment]
@weefuzzy what do you think? it sounds binary, it has 3 states... how could we phrase it to acknowledge it has veryvery few possible states ?

**Review by jamesb93 — APPROVED** [review]

**Pull request merged**
