### PR TITLE
BufSTFT RST and SC example code

### PR DESCRIPTION
**Pull request by tedmoore**

### CODE REVIEW

**Review by tremblap — CHANGES_REQUESTED** [review]
great overall!

strange formatting/rendering of source and lenght in the only_in:: sc section (is it a bug?)

**Comment by tremblap** [comment]
also there is a lot of yellow in the window due to the extra maxFFTsize (which for buffer is not existant)

**Comment by tremblap** [comment]
super cool example of reconstruction!

**Comment by tedmoore** [comment]
this can be merged after https://github.com/flucoma/flucoma-docs/pull/129

**Pull request merged**
