### PR TITLE
Enhance/selective text

### PR DESCRIPTION
**Pull request by weefuzzy**
@tedmoore 

This adds a reStructuredText 'directive' called `only_in` to provide a flexible way of having blocks that can be selectively included depending on the host.  This has the upside that we can include it anywhere where we're using rst, and also select multiple hosts (which might be helpful where Max and PD are close enough both to warrant the same bit of text but we don't want it elsewhere). 

Usage would be like (let's say we're in the descrtiption block of some object...)
```reStructuredText 

:description: 
   This fantastic object is fantastic. Sooo good. Man, I'm impressed with myself. 

   .. only-in:: sc 
      
      However, please note that in Supercollider, the immediate effect of using this object is that your feet explode. 

  .. only-in:: max pd 

     Whereas in patching languages, a picture of Dorian Gray in someone's attic gets RSI on your behalf

  And now we're back to text that's visible to all hosts  

```

Note all the whitespace and indenting. 

In rendering it should Just Work ™️  – no changes need to be made to templates. 

If you like it, feel welcome to merge it. 

@jamesb93 and @tremblap you'll probably be interested to know this exists too, but I'm waving it at Ted first as he's the one with an immediate problem to solve...

### CODE REVIEW

**Comment by tedmoore** [comment]
this is beautiful. thank you! looking forward to testing soon!

**Comment by jamesb93** [comment]
Ah this is really nice :) Good to know its around for sure.

I guess on a similar note are `pd-related` `max-related` to accompany `sc-related` still on the cards?

**Comment by weefuzzy** [comment]
> I guess on a similar note are `pd-related` `max-related` to accompany `sc-related` still on the cards?

I don't think there's anything gnarly and pythonic required for them to be used now: the respective templates would need to take account of them and do something sensible, but they should show up if that happens.

**Comment by jamesb93** [comment]
Okay, maybe if you guys can be bothered to wait that would be a good one for me to do so I stay somewhat fresh with the code? I am OOTL by design atm but i'll need to know this stuff 'ventually

**Comment by weefuzzy** [comment]
Happy to leave that to anyone else's eager paws

**Comment by tedmoore** [comment]
@jamesb93 I may need to get to this sooner as it's on the road to getting SC docs fixed up the way I want (and for beta5), but if you beat me to it, just let me know and it's all yours!

**Comment by jamesb93** [comment]
> @jamesb93 I may need to get to this sooner as it's on the road to getting SC docs fixed up the way I want (and for beta5), but if you beat me to it, just let me know and it's all yours!

I think you have `sc-related` already though don't you?

**Comment by weefuzzy** [comment]
Yeah, we've ended up talking about something else, like bad people.

**Comment by jamesb93** [comment]
> Yeah, we've ended up talking about something else, like bad people.

Lol yeah true. We'll circle around to this later @tedmoore and keep the sanity of PRs clean :P

**Comment by tedmoore** [comment]
I propose that we look at this PR and solving https://github.com/flucoma/flucoma-docs/pull/56 _after_ we merge all the YAML to rst stuff. Maybe that was the plan all along, but I'm just wrapping my head around the dependencies of PRs here.

**Review by tedmoore — APPROVED** [review]

**Comment by weefuzzy** [comment]
This is now up to date with the changes on dev, seems to be working fine. @tedmoore  suggest you play with it tomorrow and if all is good, squash + merge

**Comment by tremblap** [comment]
My 2c: I really love this syntax and the ability to have everything written in one place. I can see a workflow for post-project PRs where people can work collaboratively on a new object.

actually, I might be tempted to write that way the new skmeans object, would that make sense?

**Comment by tremblap** [comment]
the workflow of someone providing an algo with probably incomplete doc and examples. Then someone else writing a more holistic cross-cce doc. all the work you have done as a power trio on making the docs flexible and cross-cce customisable makes me happy. sorry for the love. i was proposing to use what Gerard will send, as I am used to the state of what I receive, and use that as a case study in learning the new syntax and cross platform conventions of docs and code and whatever.

**Comment by tedmoore** [comment]
This is great. Thank you @weefuzzy. Posting two things here for posterity. 

1. The command is now `only_in`, not `only-in`.
2. There needs to be an empty line under the command before the content for it to work, eg.:

Screenshot 2022-02-14 at 11 00 27

**Pull request merged**
