### PR TITLE
[Docs] Slicer Feature Objects

### PR DESCRIPTION
**Pull request by jamesb93**
Adds RST documentation for the new objects that produces features that the slicing objects use.﻿

### CODE REVIEW

**Comment by jamesb93** [comment]
If the reviewers @tedmoore and @weefuzzy are happy with the text then we can merge this as it seems to work ™️ .

**Comment by tremblap** [comment]
can we add the @padding in the doc for these - I don't see it (which doesn't mean it is not there :)

**Comment by jamesb93** [comment]
> can we add the @padding in the doc for these - I don't see it (which doesn't mean it is not there :)

done

**Comment by tremblap** [comment]
that will help autocomplete on max, thanks.

**Review by tedmoore — APPROVED** [review]
SC example code has been added to this PR

**Pull request merged**
