### PR TITLE
Rewrite for sc

### PR DESCRIPTION
**Pull request by weefuzzy**
@jamesb93 and @tedmoore 

Here is work in progress on preparing flucoma-docs' Python mess for SC doc generation, maintenance / improvement by people who aren't me. 

Normally, I like a smaller PR than this (and it might well be worth stopping and making a new one for the next bunch of work) , but unfortunately this does two main things 

1. Introduces (but not yet integrates) a `docutils` translator for converting inline restructuredText to SCDoc. I have yet to deal with links, however. 
2. Removes one of the major SC incompatibilities from the code that integrates the machine and human documentation, which was that all entity names get converted to lowercase. This is now done in the respective templates instead. 
 
I've been pretty careful throughout to ensure that changes aren't breaking existing behaviour, including full string comparisons on all the generated text for PD as I went. So I'm reasonably confident this still works as it did, modulo a couple of fixes to restructuredText strings I found in the docs. 

There's still a fair amount more to do: 
* adding SC as a host (I believe the two of you have started a template today?) 
* factoring out CCE specific stuff into sensible modules 
* tidying up the validate and merge code so that it's readable by other people 
* discovering the remaining obstacles for SC. Two starters are: 
    1. In SC FFT settings are represented as discrete parameters, unlike other hosts. So we'll need a way to cope with that 
    2. I'm not sure we have enough information from the machine yet to distinguish between all our different kinds of object (e.g. between audio in / audio out and audio in / control out). So we may need to annotate or something, pending some improvements to flucoma-core

### CODE REVIEW

**Comment by jamesb93** [comment]
I'm trawling through this just trying to come to terms with what bit does what and what I can learn. This is perhaps more of a think out loud:

`FluidRefData` now includes a number of different functions that on the surface deal with basically every kind of translation you would want to make from the text -> host wrapper's documentation format (whatever that is).

`DefaultData` hosts a number of functions that return a bunch of things that commonly arise. I assume these are things that would get shoved into the payload for the Jinja2 template?

**Comment by weefuzzy** [comment]
This is almost ready for some prodding and issue-making from others, I think. Usage-wise, it should be the same as before (i.e. the CMake targets haven't changed). But there is now a stab at generating SC docs. 

Code-wise, it's completely different and hopefully more amenable to extension and co-maintenance 😆 

There are now *some* tests (runnable with CTest), and I'll push up some documentation in due course.

**Comment by weefuzzy** [comment]
The Jinja templates for SC use template inheritance to try and make the fact that the class methods for different species of object differ so widely yield less horribleness. Hopefully it's follow-able.

**Comment by weefuzzy** [comment]
Also, all the example snippets for the SC code come from their own `scd` files, which live in `examples/sc`. This is all harvested from the current SC docs, rather than the YAML, because I think the latter is out of date. The script I used to do this is committed, so (with some editing) they can be updated again if needed.

**Comment by tedmoore** [comment]
Feeling very good about this. `MAKE_SC_REF`, `MAKE_MAX_REF`, and `MAKE_PD_REF` all seem to have worked for me. Also, `SCDoc.indexAllDocuments(true); // true flag is to clear the cache` has rendered the files, mostly without grump and they are looking very nice. Thank you thank you!

Screen Shot 2022-01-10 at 14 50 48

A few reports (I can poke at these further to investigate, but I leave here in case @weefuzzy can snipe these right off the bat):

1. `SCDoc.indexAllDocuments(true);` reports a lot of `Property setter *_ should be documented without underscore.`

For example in one of the perpetrating `.schelp` files, this section looks like:
```
METHOD:: high

  Getter for code::high::. See CODE::new::

METHOD:: high_

  Setter for code::high::. See CODE::new::
``` 
Which ends up looking like this:

Screen Shot 2022-01-10 at 15 16 11

My first observation is that it seems to have `CODE` tags in here. Also, it seems to think this is undocumented, even though it has "Getter for" and "Setter for".

In SC help files the getter-ness & setter-ness of everything is generally implied. I was looking through some other helps just now to see if there's a pattern to copy but I couldn't really find one. I guess one just generally assumes that all these property methods can get or set.

2. There were some errors (in SC on `SCDoc.indexAllDocuments(true);`).

```
ERROR: In /Users/macprocomputer/Desktop/_flucoma/code/flucoma-sc/release-packaging/HelpSource/Guides/FluidCorpusManipulationToolkit..schelp:
  At line 4: syntax error, unexpected newline, expecting text or URL
```
```
ERROR: In /Users/macprocomputer/Desktop/_flucoma/code/flucoma-sc/release-packaging/HelpSource/Guides/FluidCorpusManipulationToolkit..schelp:
  At line 4: syntax error, unexpected newline, expecting text or URL

SCDoc: Indexed 2624 documents in 1.52 seconds
-> SCDoc
ERROR: In /Users/macprocomputer/Desktop/_flucoma/code/flucoma-sc/release-packaging/HelpSource/Classes/FluidUMAP.schelp:
  At line 20: syntax error, unexpected ::, expecting end of file
```
```
ERROR: In /Users/macprocomputer/Desktop/_flucoma/code/flucoma-sc/release-packaging/HelpSource/Classes/FluidRobustScale.schelp:
  At line 79: syntax error, unexpected ARGUMENT, expecting ::
```

My suspicion from eyeballing is that cleaning up some of the `code::*::` tags that are in weird places might fix these, but thought I'd put them here, again in case they cause epiphanic visions.

3. Lastly, `MAKE_CLI_REF` barfed and didn't fill my folder:
```
[ 48%] Built target MLPRegressor
[ 48%] Built target MelBands
[ 51%] Built target NMFFilter
[ 51%] Built target NMFMatch
[ 53%] Built target NMFMorph
[ 53%] Built target Normalize
[ 55%] Built target NoveltySlice
[ 55%] Built target OnsetSlice
[ 57%] Built target PCA
[ 57%] Built target Pitch
[ 59%] Built target RobustScale
[ 59%] Built target STFTPass
[ 61%] Built target Sines
[ 61%] Built target SpectralShape
[ 63%] Built target Standardize
[ 63%] Built target Stats
[ 65%] Built target TransientSlice
[ 65%] Built target Transients
[ 65%] Making CLI ref
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/macprocomputer/Desktop/_flucoma/code/flucoma-docs/flucoma/MakeRef.py", line 99, in <module>
    main(sys.argv[1:])
  File "/Users/macprocomputer/Desktop/_flucoma/code/flucoma-docs/flucoma/MakeRef.py", line 78, in main
    index = {
  File "/Users/macprocomputer/Desktop/_flucoma/code/flucoma-docs/flucoma/MakeRef.py", line 81, in <dictcomp>
    *validate_object(
  File "/Users/macprocomputer/Desktop/_flucoma/code/flucoma-docs/flucoma/doc/validate/object.py", line 50, in validate_object
    human_data['parameters'] = validate_controls( 
  File "/Users/macprocomputer/Desktop/_flucoma/code/flucoma-docs/flucoma/doc/validate/controls.py", line 159, in validate_controls
    **kwargs.get('defaults',{}).get('controls',{})
AttributeError: 'NoneType' object has no attribute 'get'
make[3]: *** [CMakeFiles/MAKE_CLI_REF] Error 1
make[2]: *** [CMakeFiles/MAKE_CLI_REF.dir/all] Error 2
make[1]: *** [CMakeFiles/MAKE_CLI_REF.dir/rule] Error 2
make: *** [MAKE_CLI_REF] Error 2
```

**Comment by weefuzzy** [comment]
Following that little flurry, SC and CLI no longer complain about anything at this end

**Comment by tedmoore** [comment]
Thank you @weefuzzy , will test today!

**Comment by tedmoore** [comment]
Beautiful. The only error that I get now is on `SCDoc.indexAllDocuments(true);` which is for FluidUMAP:
```
ERROR: In /Users/macprocomputer/Desktop/_flucoma/code/flucoma-sc/release-packaging/HelpSource/Classes/FluidUMAP.schelp:
  At line 202: syntax error, unexpected ARGUMENT, expecting ::
```
which looks like this (here we see lines 186-204):
```
METHOD:: transformPoint

      WARNING::
    Not yet documented
    ::

ARGUMENT:: 

.. warning:: Not yet documented 



    WARNING::
    Not yet documented
    ::

ARGUMENT:: action // NOTE FROM TED --------- THIS IS ACTUALLY LINE 202 --------------------

  A function to execute when the server has completed running transformPoint
```
My guess is that it actually comes from the unclosed `warning::` tag a few lines up from there?

Also good to note that most of the instance methods for UMAP are not loading, but I am optimistic that they will once this is sorted. They're in the `FluidUMAP.schelp`!

**Comment by weefuzzy** [comment]
```
ARGUMENT:: 

.. warning:: Not yet documented 
```

Looks like it's spitting the reStructuredText warning spiel into the space where missing argument names would go but then not transforming it. That's a double badness because we can't have inline formatting in the argument name in any case.

**Comment by weefuzzy** [comment]
Ok, *that's* fixed, but now it looks like something screwy is going on with the getter / setter arguments (only warnings now though)

**Comment by weefuzzy** [comment]
Oh, it's just that the YAML has (some) hand written documentation for `action` arguments, but now that's generated by the template too.

**Comment by tedmoore** [comment]
Are we ready to merge this? I think this merge will help me move forward on SC docs.

**Comment by jamesb93** [comment]
Have you tested the other doc writers per chance? We really need to test that every repo produces workable docs before we merge. Happy to help on that front.

**Comment by tedmoore** [comment]
I have only tested SC. How about if I take CLI too and ask you to do Max and Pd?

**Comment by jamesb93** [comment]
That sounds good, CLI is very straightforward to build I think and the docs are pretty glanceable. I'll have a crack tomorrow morning UK time and let you know how it goes.

**Comment by tedmoore** [comment]
👍 🙏

**Comment by tedmoore** [comment]
CLI stuff looks great. Just eyeballed it and clicked through it some.  I noticed some of the docs didn't have some "See Also"s that I thought should exist. transientslice's html doesn't point at ampslice, but the transientslice yaml seems to think that it should?

In SC, there seems to be some confusion with with action functions and/or argument order. I'll try to read the code base to dig into this tomorrow.

```
WARNING: SCDoc: In /Users/macprocomputer/Desktop/_flucoma/code/flucoma-sc/release-packaging/HelpSource/Classes/FluidNormalize.schelp
  Broken link: 'Classes/FluidNone'
WARNING: SCDoc: In /Users/macprocomputer/Desktop/_flucoma/code/flucoma-sc/release-packaging/HelpSource/Classes/FluidNormalize.schelp
  Method -fitTransform has arg named 'destDataSet', but doc has 'argument:: action'.
WARNING: SCDoc: In /Users/macprocomputer/Desktop/_flucoma/code/flucoma-sc/release-packaging/HelpSource/Classes/FluidNormalize.schelp
  Method -fitTransform has arg named 'action', but doc has 'argument:: destDataSet'.
WARNING: SCDoc: In /Users/macprocomputer/Desktop/_flucoma/code/flucoma-sc/release-packaging/HelpSource/Classes/FluidNormalize.schelp
  Method -transform has arg named 'destDataSet', but doc has 'argument:: action'.
WARNING: SCDoc: In /Users/macprocomputer/Desktop/_flucoma/code/flucoma-sc/release-packaging/HelpSource/Classes/FluidNormalize.schelp
  Method -transform has arg named 'action', but doc has 'argument:: destDataSet'.
WARNING: SCDoc: In /Users/macprocomputer/Desktop/_flucoma/code/flucoma-sc/release-packaging/HelpSource/Classes/FluidNormalize.schelp
  Method -transformPoint has arg named 'destBuffer', but doc has 'argument:: action'.
WARNING: SCDoc: In /Users/macprocomputer/Desktop/_flucoma/code/flucoma-sc/release-packaging/HelpSource/Classes/FluidNormalize.schelp
  Method -transformPoint has arg named 'action', but doc has 'argument:: destBuffer'.
WARNING: SCDoc: In /Users/macprocomputer/Desktop/_flucoma/code/flucoma-sc/release-packaging/HelpSource/Classes/FluidNormalize.schelp
  Method -load has arg named 'dict', but doc has 'argument:: data'.
WARNING: SCDoc: In /Users/macprocomputer/Desktop/_flucoma/code/flucoma-sc/release-packaging/HelpSource/Classes/FluidNormalize.schelp
  Method -read has arg named 'filename', but doc has 'argument:: path'.
WARNING: SCDoc: In /Users/macprocomputer/Desktop/_flucoma/code/flucoma-sc/release-packaging/HelpSource/Classes/FluidNormalize.schelp
  Method -write has arg named 'filename', but doc has 'argument:: path'.
WARNING: SCDoc: In /Users/macprocomputer/Desktop/_flucoma/code/flucoma-sc/release-packaging/HelpSource/Classes/FluidHPSS.schelp
  Broken link: 'Guides/FluCoMa'
WARNING: SCDoc: In /Users/macprocomputer/Desktop/_flucoma/code/flucoma-sc/release-packaging/HelpSource/Classes/FluidHPSS.schelp
  Broken link: 'Guides/FluidDecomposition'
WARNING: SCDoc: In /Users/macprocomputer/Desktop/_flucoma/code/flucoma-sc/release-packaging/HelpSource/Classes/FluidHPSS.schelp
  Method *ar has 18 args, but doc has 9 argument:: tags.
WARNING: SCDoc: In /Users/macprocomputer/Desktop/_flucoma/code/flucoma-sc/release-packaging/HelpSource/Classes/FluidHPSS.schelp
  Method *ar has arg named 'in', but doc has 'argument:: harmFilterSize'.
WARNING: SCDoc: In /Users/macprocomputer/Desktop/_flucoma/code/flucoma-sc/release-packaging/HelpSource/Classes/FluidHPSS.schelp
  Method *ar has arg named 'harmFilterSize', but doc has 'argument:: percFilterSize'.
WARNING: SCDoc: In /Users/macprocomputer/Desktop/_flucoma/code/flucoma-sc/release-packaging/HelpSource/Classes/FluidHPSS.schelp
  Method *ar has arg named 'percFilterSize', but doc has 'argument:: maskingMode'.
WARNING: SCDoc: In /Users/macprocomputer/Desktop/_flucoma/code/flucoma-sc/release-packaging/HelpSource/Classes/FluidHPSS.schelp
  Method *ar has arg named 'maskingMode', but doc has 'argument:: harmThresh'.
WARNING: SCDoc: In /Users/macprocomputer/Desktop/_flucoma/code/flucoma-sc/release-packaging/HelpSource/Classes/FluidHPSS.schelp
  Method *ar has arg named 'harmThreshFreq1', but doc has 'argument:: percThresh'.
WARNING: SCDoc: In /Users/macprocomputer/Desktop/_flucoma/code/flucoma-sc/release-packaging/HelpSource/Classes/FluidHPSS.schelp
  Method *ar has arg named 'harmThreshAmp1', but doc has 'argument:: fftSettings'.
WARNING: SCDoc: In /Users/macprocomputer/Desktop/_flucoma/code/flucoma-sc/release-packaging/HelpSource/Classes/FluidHPSS.schelp
  Method *ar has arg named 'harmThreshFreq2', but doc has 'argument:: maxFFTSize'.
WARNING: SCDoc: In /Users/macprocomputer/Desktop/_flucoma/code/flucoma-sc/release-packaging/HelpSource/Classes/FluidHPSS.schelp
  Method *ar has arg named 'harmThreshAmp2', but doc has 'argument:: maxHarmFilterSize'.
WARNING: SCDoc: In /Users/macprocomputer/Desktop/_flucoma/code/flucoma-sc/release-packaging/HelpSource/Classes/FluidHPSS.schelp
  Method *ar has arg named 'percThreshFreq1', but doc has 'argument:: maxPercFilterSize'.
```

**Comment by weefuzzy** [comment]
> CLI stuff looks great. Just eyeballed it and clicked through it some. I noticed some of the docs didn't have some "See Also"s that I thought should exist. transientslice's html doesn't point at ampslice, but the transientslice yaml seems to think that it should?

The CLI should remove the `see-also`s for thngs that aren't in the CLI (all the non-buf* objects + bufcompose) but maybe it's being overzealous? 

> In SC, there seems to be some confusion with with action functions and/or argument order. I'll try to read the code base to dig into this tomorrow.

It's because there's redundant documentation of `action` functions in the the YAML (https://github.com/flucoma/flucoma-docs/pull/24#issuecomment-1010209577)

**Comment by jamesb93** [comment]
`pd` works.

**Comment by jamesb93** [comment]
I've noticed that this commented out in the `CMakeLists.txt`:

https://github.com/flucoma/flucoma-max/blob/5dbca51bbab24cd0861456cea5043c887457c3f6/CMakeLists.txt#L96

**Comment by weefuzzy** [comment]
`MAKE_MAX_REF` should still result in a `max_ref` folder in the build directory though.

**Comment by jamesb93** [comment]
> `MAKE_MAX_REF` should still result in a `max_ref` folder in the build directory though.

I don't think `MAKE_MAX_REF` was being called under the hood when I ran `ninja install` though. When I ran it manually the folder certainly appeared.

**Comment by jamesb93** [comment]
> I've noticed that this commented out in the `CMakeLists.txt`:
> 
> https://github.com/flucoma/flucoma-max/blob/5dbca51bbab24cd0861456cea5043c887457c3f6/CMakeLists.txt#L96

After uncommenting these lines docs are generated from `ninja` and `ninja install`

**Comment by weefuzzy** [comment]
Then that's a distinct problem from whether or not this PR is working for generating Max docs like it used to. Use `MAKE_MAX_REF` and we can return to the issue of whether `install` should be triggering this in the max repo.

**Comment by jamesb93** [comment]
> Then that's a distinct problem from whether or not this PR is working for generating Max docs like it used to. Use `MAKE_MAX_REF` and we can return to the issue of whether `install` should be triggering this in the max repo.

Yeah I can flag another issue in the appropriate place (Max repo presumably). But I think the document generator does indeed work and I just had to hone the source of the problem and discern if the generator was dying in the arse or the CMake was.

**Review by jamesb93 — APPROVED** [review]

**Comment by weefuzzy** [comment]
Importantly, are the Max docs correct?

**Comment by jamesb93** [comment]
> Importantly, are the Max docs correct?

Yep! I wasn't clear enough - the generation works and the docs it produces look right. In some cases I think it actually fixed some issues that I noticed before, like a `<ul>` that was wonky in `spectralshape.maxref`.

**Comment by weefuzzy** [comment]
And is auto-complete working for flucoma objects against these docs? If so, we're probably golden

**Comment by jamesb93** [comment]
Oops, I found a bug after the fact @weefuzzy  🙈

image

Which looks like an unresolved convert from the object token to a Max-y representation?

```
<description>
<p>
Perform regression between
<o>Unresolved lookup (DataSets<DataSet>)</o> 
using a Multi-Layer Perception neural network.
</p>
</description>
```

**Comment by weefuzzy** [comment]
Hmm. More that leaving the original unresolved reStructuredText (which has a `<DataSet>` in it) then fucks the parsing for syntaxes that treat `<...>` as an opening. I guess the thing to do is make the unresolved rst into a literal block.

**Comment by weefuzzy** [comment]
Ok, there's some general badness about how / when to deal with escaping `<` and `>` in XML / HTML output, which I will figure out. 

However, there's a more general question we can figure out between ourselves whilst I think about that: how do we pluralize cross references to objects? 

**The problem** is that just sticking an 's' on the end breaks rst parsing, so :fluid-object:`DataSet`s breaks. 

> The specific issue we're having here is a sideshow to my attempted solution, which is that the rst way to specify different display text from a link target is to spell it `display this text<link_to_this_target>`, but my code isn't handling that properly (I thought docutils would do it for me) 

So: dear readers, what's a uncumbersome way we could spell a plural object cross reference in our documentation? A different rst role? (`:fluid-objects:` rather than `fluid-object`). Don't like it. 

Whilst we're about it, there's a second question about cross references to specific attributes / methods. It's not possible in the Max doc format to generate links that point to specific bits of *other* objects, but it is in HTML (obviously)  and scdoc. At present `Normalize`, `Standardize`,`PCA` and `KMeans` docs all contain internal refs to  methods that are spelled in scdoc syntax (using `#`). How do we want to handle these in general?

**Comment by jamesb93** [comment]
> Ok, there's some general badness about how / when to deal with escaping `<` and `>` in XML / HTML output, which I will figure out.
> 
> However, there's a more general question we can figure out between ourselves whilst I think about that: how do we pluralize cross references to objects?
> 
> **The problem** is that just sticking an 's' on the end breaks rst parsing, so :fluid-object:`DataSet`s breaks.
> 
> > The specific issue we're having here is a sideshow to my attempted solution, which is that the rst way to specify different display text from a link target is to spell it `display this text<link_to_this_target>`, but my code isn't handling that properly (I thought docutils would do it for me)
> 
> So: dear readers, what's a uncumbersome way we could spell a plural object cross reference in our documentation? A different rst role? (`:fluid-objects:` rather than `fluid-object`). Don't like it.
>  

I'm not familiar enough with what we _can_ do in RST. I suppose this has to be solved at the parsing level more likely?

> Whilst we're about it, there's a second question about cross references to specific attributes / methods. It's not possible in the Max doc format to generate links that point to specific bits of _other_ objects, but it is in HTML (obviously) and scdoc. At present `Normalize`, `Standardize`,`PCA` and `KMeans` docs all contain internal refs to methods that are spelled in scdoc syntax (using `#`). How do we want to handle these in general?

Can we leverage `:ref:`MethodName type syntax?

**Comment by weefuzzy** [comment]
Not for the first time, I was making it too complicated 😆 We can deal with plurals easily by escaping the 's' immediately following the parsed text to stop it breaking. So while this breaks
```reStructuredText
:fluid-obj:`DataSet`s
```
this is fine
```reStructuredText
:fluid-obj:`DataSet`\s
```

> Can we leverage :ref:MethodName type syntax?

You mean can we make a new `role` (`:something:`) for linking to attributes / messages? Sure: I guess the limitation is that it would need to be part of the object in question (to work in Max).

**Comment by jamesb93** [comment]
> Not for the first time, I was making it too complicated 😆 We can deal with plurals easily by escaping the 's' immediately following the parsed text to stop it breaking. So while this breaks
> 
> ```
> :fluid-obj:`DataSet`s
> ```
> 
> this is fine
> 
> ```
> :fluid-obj:`DataSet`\s
> ```

Nice that there is a native solution :)

**Comment by tedmoore** [comment]
🎉

**Comment by jamesb93** [comment]
A great PR, really looking forward to working more in the mud with you on docs and eventually writing an adapter for learn with @tedmoore .

Thanks @weefuzzy !! 🚀

**Pull request merged**
